print("Hello, Debbie")
print("Hello, Debbie, this is your first project")
print("It is Monday")
print("Today is Tuesday")
print("I love how Wednesday is going")
print("Thursday is terrific")
print("We go again on Friday")
print("git commandsAssignment" "git init")
print("git clone <repository_url>")
print("git add .")
print("git status")
print("git log")