print("Hello, Debbie")
print("Hello, Debbie, this is your first project")
print("It is Monday")
print("Today is Tuesday")
print("I love how Wednesday is going")
print("Thursday is terrific")
print("We go again on Friday")
print("git commandsAssignment" "git init")
print("git clone <repository_url>")
print("git add .")
print("git status")
print("git log")
print("git diff")
print("git reset <file>")
print("git rm <file>")
print("git mv <old name> <new name>")
print("Branching and Merging Git Commands")
print("git branch")
print("git branch <branch_name>")
print("git checkout <branch_name>")
print("git merge <branch_name>")
print("git rebase <branch_name>")
print("git stash")
print("git stash pop")
print("Git commands for Remote Repositories")
print("git remote -v")
print("git remote add <name> <url>")
print("git push origin <branch>")
print("git fetch")
print("git pull")